-- Dummy Developer
INSERT INTO DEVELOPER (NAME, ACTIVE) VALUES ('Volkan', true);

-- Bug priorities
INSERT INTO BUG_PRIORITY (DESCRIPTION) VALUES ('Critical');
INSERT INTO BUG_PRIORITY (DESCRIPTION) VALUES ('Major');
INSERT INTO BUG_PRIORITY (DESCRIPTION) VALUES ('Minor');

-- Bug statuses
INSERT INTO BUG_STATUS (DESCRIPTION) VALUES ('New');
INSERT INTO BUG_STATUS (DESCRIPTION) VALUES ('Verified');
INSERT INTO BUG_STATUS (DESCRIPTION) VALUES ('Resolved');

-- Story points
INSERT INTO STORY_POINT (POINTVALUE) VALUES (1); 
INSERT INTO STORY_POINT (POINTVALUE) VALUES (2); 
INSERT INTO STORY_POINT (POINTVALUE) VALUES (3); 
INSERT INTO STORY_POINT (POINTVALUE) VALUES (5); 
INSERT INTO STORY_POINT (POINTVALUE) VALUES (8); 

-- Story status
INSERT INTO STORY_STATUS (DESCRIPTION) VALUES ('New');
INSERT INTO STORY_STATUS (DESCRIPTION) VALUES ('Estimated');
INSERT INTO STORY_STATUS (DESCRIPTION) VALUES ('Completed');
